# This is the configuration used to check the rubocop source code.

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false


Layout/SpaceInLambdaLiteral:
  Enabled: false  

