language: ruby
env: 
  - RAILS_ENV=test
before_script:
  - psql -c 'create database gtbox_labs_test;' -U postgres
  - rake db:migrate

before_install:
  - gem update --system
  - gem install bundler
  
install:
  - yarn install
  - bundle install --jobs=3 --retry=3

services:
  - postgresql
