version: '3'
services:
  gtbox-labs:
    build:
      context: ../
    environment:
      app_database_host: db
      RAILS_LOG_TO_STDOUT: 1
      RAILS_SERVE_STATIC_FILES: 1
    ports:
      - "80:80"
    expose:
      - "80"
    links:
      - db:db
    volumes:
      - ..:/src/gospeltoolbox/labs
    links:
      - db:db

  db:
    image: postgres
